version: "3.8"
services:
  database:
    container_name: bda_gr4_database
    build:
      context: ./postgres-db/
    networks:
      - domain_analysis_network_gr4
  dig_ms:
    container_name: bda_gr4_dig_ms
    build:
      context: ./dig-microservice/
    networks:
      - domain_analysis_network_gr4
    restart:
      on-failure
  statistics_service:
    container_name: bda_gr4_statistics_service
    build:
      context: ./statistics-service
    depends_on:
      - database
    networks:
      - domain_analysis_network_gr4
    restart:
      on-failure
  dashboard:
    container_name: bda_gr4_dashboard
    build:
      context: ./dashboard/
    depends_on:
      - dig_ms
      - statistics_service
    networks:
      - domain_analysis_network_gr4
    ports:
      - 8321:80
  spark:
    container_name: bda_gr4_spark
    ports:
      - 8888:8888
    networks:
      - domain_analysis_network_gr4
    build:
      context: ./pyspark-analyse/
    depends_on:
      - database
    environment:
      - JUPYTER_ENABLE_LAB=1
    volumes:
      - ../data:/home/jovyan/work/data
      - ./pyspark-analyse/notebooks:/home/jovyan/work/notebooks
    # TODO: rename pyspark dir as soon as it is safe regarding merge conflicts

networks:
  domain_analysis_network_gr4:
    name: domain_analysis_network_gr4

# TODO Add further services
