version: "3.8"
services:
  dashboard:
    container_name: dashboard
    build:
      context: ./dashboard/
    networks:
      - domain_analysis_network
    ports:
      - "8321:80"

networks:
  domain_analysis_network:
    name: domain_analysis_network

# TODO Add further services

# docker-compose -p "bda-gr4-domain-analysis" up -d
# TODO doc
# Better image management (no new image with sha only) with "docker-compose" instead of "docker compose" (Docker tool)
