FROM jupyter/pyspark-notebook
COPY *.ipynb /home/jovyan/work/notebooks/
COPY real_domains.csv /home/jovyan/work/data/

# TODO Fix: java.sql.SQLException: No suitable driver in last chunk

# TODO Mount? => data? notebooks? both?
# TODO /data good practice?
