on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  assignment-zip-artifact:
    runs-on: ubuntu-latest
    name: Create ZIP to be handed in
    steps:
      - uses: actions/checkout@v2
#      - name: Compile LaTeX file to PDF
#      - name: Convert PPTX to PDF
#        run: |
#          sudo apt-get install unoconv
#          unoconv -f pdf presentation.pptx
      - name: Rename files
        run: |
          rsync -Rr . ./YYYY-MM-DD-Group-4-Domains-Analysis-Source
#          mv presentation.pdf YYYY-MM-DD-Group-4-Domains-Analysis-Presentation.pdf
#         ... YYYY-MM-DD-Group-4-Domains-Analysis-Conceptual-Documentation.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: YYYY-MM-DD-Group-4-Domains-Analysis
          path: |
            YYYY-MM-DD-Group-4-Domains-Analysis-Source
#           YYYY-MM-DD-Group-4-Domains-Analysis-Presentation.pdf
#           YYYY-MM-DD-Group-4-Domains-Analysis-Conceptual-Documentation.pdf
          retention-days: 1

# TODO Use actual date instead of YYYY-MM-DD
